name: github-pipelines
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
        working-directory: ./pigeon-backend
  backend-linting:
    name: Backend Linting
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run lint
          npm run prettier
        working-directory: ./pigeon-backend
